services:
  # Caddy Reverse Proxy Service (for cloud deployment)
  caddy:
    image: caddy:2-alpine
    container_name: buffrsign-caddy
    restart: always
    ports:
      - 80:80/tcp
      - 443:443/tcp
    expose:
      - 2019/tcp
      - 443/tcp
      - 443/udp
      - 80/tcp
    environment:
      - AGENT_API_HOSTNAME=${AGENT_API_HOSTNAME:-api.sign.buffr.ai}
      - FRONTEND_HOSTNAME=${FRONTEND_HOSTNAME:-sign.buffr.ai}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL:-george@buffr.ai}
      - API_PUBLIC_ORIGIN=${API_PUBLIC_ORIGIN:-https://api.sign.buffr.ai}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data:rw
      - caddy_config:/config:rw
    depends_on:
      - buffrsign-api
      - buffrsign-frontend
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:2019/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    networks:
      - buffrsign-network

volumes:
  caddy_data:
  caddy_config:
