apiVersion: apps/v1
kind: Deployment
metadata:
  name: buffrsign-backend
  namespace: buffrsign
spec:
  replicas: 2
  selector:
    matchLabels:
      app: buffrsign-backend
  template:
    metadata:
      labels:
        app: buffrsign-backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/thependalorian/buffrsign-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: buffrsign-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: buffrsign-secrets
              key: redis-url
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: buffrsign-backend-svc
  namespace: buffrsign
spec:
  selector:
    app: buffrsign-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP
