[project]
name = "buffrsign-api"
version = "0.1.0"
description = "BuffrSign FastAPI placeholder"
requires-python = ">=3.10"
dependencies = [
  "fastapi~=0.111",
  "uvicorn[standard]~=0.30"
]

[tool.uvicorn]
factory = true
